### ISSUE TITLE
InventoryPets crashes when trying to give XP-Plus items. (Compatability issue)

### ISSUE THREAD

**Issue by Mrbysco** [Poke1650/XP-Plus#6]
Minecraft Version: 1.10.2

Forge Version: 12.18.3.2254

Modpack: Foolcraft v1.2.1 

Crashlogs (via Pastebin, Hastebin etc.):
https://pastebin.com/LCM4kpkk

Steps to reproduce:
Install InventoryPets, get the Illuminati pet. Set config so it only has chance to give craft able items.
Wait till it tries to give you a XP-Plus item.

Multiplayer or Singleplayer?:
Multiplayer

**Comment by antoinegag** [comment]
Found the issue, will be fixed in next update.
Thanks
